### ISSUE TITLE
Resize no work

### ISSUE THREAD

**Issue by lettfeti** [hjalti/ruv-cli#1]
As a user of ruv i take my mac laptop and shake it a bit and then try to resize the curses window.

         Traceback (most recent call last):
                                                                  File "/usr/local/lib/python3.6/site-packages/ruv/choose.py", line 297, in choose
                                                                                                                                                      logging.debug('key pressed %s (%s), keyname: %s', x, bin(x), curses.keyname(x))
                        ValueError: invalid key number
            
also the resize doesn't work

**Comment by hjalti** [comment]
Resize might work now (0.1.4)
